name: Build Image and Publish to Dockerhub & GPR

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test'
permissions:
  contents: read

jobs:
  image:
    name: Build Image from Dockerfile and binaries
    runs-on: ubuntu-latest
    steps:

      # environment
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # get image tag name
      - name: Get Image Tag Name
        run: |
          if [ x${{ github.event.inputs.tag }} == x"" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to the GPR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GPR_TOKEN }}

      # prepare image tags
      - name: Prepare Image Tags
        run: |
          echo "TAG_CFDDNS=aircross/cfddns:${{ env.TAG_NAME }}" >> $GITHUB_ENV
          echo "TAG_CFDDNS_GPR=ghcr.io/aircross/cfddns:${{ env.TAG_NAME }}" >> $GITHUB_ENV
          echo "TAG_CFDDNS_LATEST=aircross/cfddns:latest" >> $GITHUB_ENV
          echo "TAG_CFDDNS_GPR_LATEST=ghcr.io/aircross/cfddns:latest" >> $GITHUB_ENV

      - name: Build and push cfddns
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ${{ env.TAG_CFDDNS }}
            ${{ env.TAG_CFDDNS_LATEST }}
            ${{ env.TAG_CFDDNS_GPR }}
            ${{ env.TAG_CFDDNS_GPR_LATEST }}

      - name: Sync README.md
        uses: actionhippie/pushrm@v1
        with:
          provider: dockerhub
          target: ${{ secrets.DOCKERHUB_USERNAME }}/cfddns
          readme: README.md
          description: Docker readme for cfddns
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}