name: build-go-binary-when-new-release

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # linux windows darwin freebsd android
        goos: [linux, windows, darwin, freebsd, android] # 需要打包的系统
        # 386 amd64 arm arm64 mips64 mips64le mips mipsle riscv64 loong64
        # 386, amd64, arm, arm64, mips64, mips64le, mips, mipsle, riscv64, loong64
        goarch: [386, amd64, arm, arm64, mips64, mips64le, mips, mipsle, riscv64, loong64] # 需要打包的架构
        # exclude: # 排除某些平台和架构
        #   - goarch: arm64
        #     goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GPR_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.23.3 # 可以指定编译使用的 Golang 版本
          binary_name: "cfddns" # 可以指定二进制文件的名称
          extra_files: README.md conf.toml.example # 需要包含的额外文件
