name: goreleaser

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      # - name: Grant execute permission to the package
      #   run: chmod +x ./package.sh
          
      - name: Make All
        run: |
          ./package.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GPR_TOKEN }}
          body_path: ./Release.md
          make_latest: true
          files: |
            ./packages/**
            ./Release.md

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v5
      #   with:
      #     version: latest
      #     args: release --clean --release-notes=./Release.md
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
